
logo: ./logo.jpg
title: ProgramadorCansado.php
description: Antes de olhar para o código-fonte, é importante olhar o funcionamento da mente, caso contrário, ela vai bugar mais que o código-fonte.
theme: jekyll-theme-slate
